functionsDirectory = "/Users/iseong-wan/phoneplaza-premium-landing/netlify/functions"
functionsDirectoryOrigin = "config-v1"
redirectsOrigin = "config"
plugins = []
headers = []

[build]
publish = "/Users/iseong-wan/phoneplaza-premium-landing"
publishOrigin = "default"
functions = "/Users/iseong-wan/phoneplaza-premium-landing/netlify/functions"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[functions]

[functions."*"]

[[redirects]]
from = "/s/naunjeom"
to = "https://www.ictmarket.or.kr:8443/ajax/ajax3.do?id=PRE0000179608&seq=1&yn=1"
status = 302.0
force = true

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/s/miryongjeom"
to = "https://www.ictmarket.or.kr:8443/ajax/ajax3.do?id=PRE0000053595&seq=1&yn=1"
status = 302.0
force = true

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/s/mijeongjeom"
to = "https://www.ictmarket.or.kr:8443/ajax/ajax3.do?id=PRE0000165400&seq=1&yn=1"
status = 302.0
force = true

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/s/seocheonjeom"
to = "https://www.ictmarket.or.kr:8443/ajax/ajax3.do?id=PRE0000114646&seq=1&yn=1"
status = 302.0
force = true

[redirects.query]

[redirects.conditions]

[redirects.headers]